trigger:
- develop

pool:
  name: SaGurpool

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '-c Release'
